# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

mod_id=storagenetwork
curse_id=268495
mod_version=1.12.2
mc_version=1.20.1

# NEO
forge_version=47.1.104

mod_name=storagenetwork
mod_group_id=com.lothrazar.storagenetwork

mapping_channel=official
mapping_version=1.20.1

flib_version=0.0.14
flib_file=5495793
patchouli_version=84
jei_version=15.3.0.4
emi_version=1.0.21
curios_version=5.7.2
