# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false


#use this if the gradle build has ' Could not find tools.jar. Please check that _____ contains a valid JDK installation '
#org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-8.0.322.6-hotspot

# as needed run/server.properties : online-mode=false
# implementation fg.deobf("curse.maven:simple-storage-network-268495:3163007")


mod_id=storagenetwork
curse_id=268495
mod_version=1.12.2

mc_version=1.20.1

# NEO
forge_version=47.1.104

mod_name=storagenetwork
mod_group_id=com.lothrazar.storagenetwork

mapping_channel=official
mapping_version=1.20.1


flib_version=0.0.14
flib_file=5495793
patchouli_version=84
jei_version=15.3.0.4
emi_version=1.0.21
curios_version=5.7.2


