
flib_version=0.2.0
flib_file=8117455

mod_id=storagenetwork
curse_id=268495
mod_version=1.13.0
mod_name=storagenetwork
mod_group_id=com.lothrazar.storagenetwork
curse_slug=simple-storage-network
modrinth_id=simple-storage-network
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod



emi_version=1.1.23+1.21.1
