

flib_version=0.2.7
flib_file=8309035

mod_id=storagenetwork
curse_id=268495
mod_version=1.13.1
mod_name=storagenetwork
mod_group_id=com.lothrazar.storagenetwork
curse_slug=simple-storage-network
modrinth_id=simple-storage-network
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod



emi_version=1.1.23+1.21.1

# Refined Storage 2.0.8 (project 243076, file 8105115)
rs_id=8105115
# Applied Energistics 2 19.2.17 (project 223794, file 7027323)
ae2_id=7027323
